apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  labels:
    app: flask-microservice
spec:
  type: LoadBalancer
  selector:
    app: flask-microservice
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  sessionAffinity: None
